apiVersion: v1
kind: Pod
metadata:
    labels:
      name: build-pod
spec:
  serviceAccountName: jenkins-my-bloody-jenkins
  containers:
      - name: docker
        image: docker:19.03
        command:
          - cat
        tty: true
        privileged: true
        volumeMounts:
          - name: dockersock
            mountPath: /var/run/docker.sock
      - name: helm
        image: lachlanevenson/k8s-helm:latest
        command:
          - cat
        tty: true
      - name: python
        image: r-whites/python-testing:latest
        command:
          - cat
        tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: m2
      hostPath:
        path: /root/.m2